name: CICD Dev

on:
  push:
    branches:
      - develop
      - dev
      # Optional
      - main
      - master
    paths-ignore:
      - '*.md'
      - .vscode/**
      - LICENSE
  # Optional, manual trigger
  workflow_dispatch:
# Optional, set working directory
# defaults:
#   run:
#     working-directory: ./cdk8s
jobs:
  # A demo job,
  publish_to_docker_hub:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Build, Publish
        run: echo 'published'

  # Optional, Test
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: publish_to_docker_hub
    steps:
      - name: Test
        run: echo 'Tested'

  # Deploy to Dev ENV
  deploy_dev:
    name: Deploy to Dev ENV
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build, Test, Deploy
        run: echo 'Deployed'
